### ISSUE TITLE
Clicking on the block tune alignment tool submits the form

### ISSUE THREAD

**Issue by michaelcais** [kaaaaaaaaaaai/editorjs-alignment-blocktune#4]
When an Editor.js instance is inside a form, clicking on the block tune alignment tool submits the form. The block tune alignment tool uses the `<button>` tag but does not have a specified type as "button" so it defaults to "submit". Please add `type="button"` attribute to the tag.

**Comment by Woloja** [comment]
yep, iam too have this problem(

**Comment by Kris-Simpson** [comment]
have the same problem

**Comment by kaaaaaaaaaaai** [comment]
@michaelcais  @Woloja @Kris-Simpson can u pull request?

**Comment by Fatin-Shahriare-Sium** [comment]
how to add type='button'?

**Comment by brtchkv** [comment]
Same here. Will it be fixed?

**Comment by kaaaaaaaaaaai** [comment]
thanku meeeeeeeeeeeeeeeeeeeeeeeeeeeens.


releaseed #5 
v1.0.3
